[package]
name = "twilight-aurora"
version = "0.1.0"
edition = "2024"
authors = ["Adithya Udupa <maskddev@gmail.com>"]
description = "A wrapper crate for the twilight ecosystem providing convenient utilities for bot development."
documentation = "https://docs.rs/twilight-aurora"
repository = "https://github.com/MaskdDev/twilight-aurora"
readme = "README.md"
license = "MIT"
keywords = ["discord", "discord-api", "utility", "twilight"]

[dependencies]
derive_builder = "0.20.2"
futures-util = "0.3.34"
thiserror = "2.0.20"
tokio = "1.53.1"
tracing = "0.1.44"
twilight-gateway = "0.17.1"
twilight-http = "0.17.1"
twilight-model = "0.17.1"
async-trait = "0.1.92"
